### ISSUE TITLE
Consider using final vals for Platform.{isJvm,isJs}

### ISSUE THREAD

**Issue by sjrd** [InTheNow/catalysts#22]
Just browsing through the code, I noticed you use macros to implement `Platform.isJvm` and `Platform.isJs`. The macros are different on both platforms and return trivial constant expressions: [JVM version](https://github.com/InTheNow/catalysts/blob/master/platform/jvm/src/main/scala/catalysts/Platform_jvm.scala) and [JS version](https://github.com/InTheNow/catalysts/blob/master/platform/js/src/main/scala/catalysts/Platform_js.scala).

You can achieve precisely the same result without macros, with `final val`s without type ascription. JVM version:
```scala
object Platform {
  final val isJvm = true
  final val isJs = false
}
```
and you guess the JS version.

final vals without type ascription whose right-hand-side is a literal, or can be constant-folded away, are themselves constant-folded at use site by `typer`, so you get exactly the same tree after typer as if you use the macros.

**Comment by InTheNow** [comment]
Thanks @sjrd - I'll add an "improvement" label to this, once we've added some labels ;)

**Comment by InTheNow** [comment]
@ochrons Do you want to have a crack at this? If not, I can do tomorrow
